name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install lightgallery
      - run: mkdocs gh-deploy --force
          
      # clone other branch (gh-pages)
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Clone Branch
          branch: deploy
          push_options: '--force'
