name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install lightgallery
      - run: mkdocs gh-deploy --force
      - uses: stefh/ghaction-CompressFiles@v1
        with:
          path: deploy
          depth: 10        
          extensions: '.css,.html,.js,.map,.ttf,.otf,.eot,.svg,.woff,.woff2,.xml,.txt,.md'
          tools: 'brotli,gzip'
